export const INCREASE = 'INCREASE'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SELECT_ARTICLES = 'SELECT_ARTICLES'

export const SELECT_DATES = 'SELECT_DATES'

export const SELECT_ARTICLES_BY_DATES = 'SELECT_ARTICLES_BY_DATES'
